multiline_comment|/*&n; * GIT - The information manager from hell&n; *&n; * Copyright (C) Linus Torvalds, 2005&n; */
macro_line|#include &quot;cache.h&quot;
macro_line|#include &quot;diff.h&quot;
macro_line|#include &quot;commit.h&quot;
macro_line|#include &quot;revision.h&quot;
macro_line|#include &quot;builtin.h&quot;
DECL|variable|diff_files_usage
r_static
r_const
r_char
id|diff_files_usage
(braket
)braket
op_assign
l_string|&quot;git-diff-files [-q] [-0/-1/2/3 |-c|--cc|-n|--no-index] [&lt;common diff options&gt;] [&lt;path&gt;...]&quot;
id|COMMON_DIFF_OPTIONS_HELP
suffix:semicolon
DECL|function|cmd_diff_files
r_int
id|cmd_diff_files
c_func
(paren
r_int
id|argc
comma
r_const
r_char
op_star
op_star
id|argv
comma
r_const
r_char
op_star
id|prefix
)paren
(brace
r_struct
id|rev_info
id|rev
suffix:semicolon
r_int
id|nongit
op_assign
l_int|0
suffix:semicolon
id|prefix
op_assign
id|setup_git_directory_gently
c_func
(paren
op_amp
id|nongit
)paren
suffix:semicolon
id|init_revisions
c_func
(paren
op_amp
id|rev
comma
id|prefix
)paren
suffix:semicolon
id|git_config
c_func
(paren
id|git_default_config
)paren
suffix:semicolon
multiline_comment|/* no &quot;diff&quot; UI options */
id|rev.abbrev
op_assign
l_int|0
suffix:semicolon
id|argc
op_assign
id|setup_revisions
c_func
(paren
id|argc
comma
id|argv
comma
op_amp
id|rev
comma
l_int|NULL
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|rev.diffopt.output_format
)paren
id|rev.diffopt.output_format
op_assign
id|DIFF_FORMAT_RAW
suffix:semicolon
r_return
id|run_diff_files_cmd
c_func
(paren
op_amp
id|rev
comma
id|argc
comma
id|argv
)paren
suffix:semicolon
)brace
eof
